import { useEffect, useState } from 'react';
import AppShell from '@/components/layout/AppShell';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import { useAuth } from '@/features/auth/hooks/useAuth';
import { organizationApi, type Member, type Organization, type Authority } from '@/features/organization/organizationApi';
const authorities: Authority[] = ['MANAGE_PROFILE', 'MANAGE_MEMBERS', 'MANAGE_CONTENT', 'ISSUE_CERTIFICATES'];
export default function OrganizerPage() {
    const { user } = useAuth(); const [org, setOrg] = useState<Organization | null>(null), [members, setMembers] = useState<Member[]>([]), [canManage, setCanManage] = useState(false), [memberId, setMemberId] = useState(''), [message, setMessage] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
    async function load() { try { const o = await organizationApi.mine(); setOrg(o); const grant = await organizationApi.can(o.id, 'MANAGE_MEMBERS'); setCanManage(grant.allowed); if (grant.allowed) setMembers(await organizationApi.members(o.id)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load organization'); } }
    useEffect(() => { void load(); }, []);
    async function run(fn: () => Promise<unknown>) { setBusy(true); setError(''); setMessage(''); try { await fn(); setMessage('Saved successfully.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Action failed'); } finally { setBusy(false); } }
    return <AppShell><div className="org-workspace"><div className="org-workspace-header"><span className="org-eyebrow">ORGANIZER WORKSPACE</span><h1>{org?.displayName ?? 'Organization'}</h1><p>Manage your organization profile and team permissions.</p></div>{error && <p className="org-error" role="alert">{error}</p>}{message && <p className="org-success" role="status">{message}</p>}{!org ? <p>Loading organization…</p> : <><section className="org-panel"><h2>Organization profile</h2><p>Approval: <strong>{org.status}</strong></p><form className="org-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); void run(() => organizationApi.update(org.id, { displayName: String(data.get('displayName')), website: String(data.get('website')), industry: String(data.get('industry')), contactPhone: String(data.get('contactPhone')) })); }}><Input name="displayName" label="Display name" required defaultValue={org.displayName} /><Input name="industry" label="Industry" required defaultValue={org.industry} /><Input name="website" label="Website" type="url" defaultValue={org.website ?? ''} /><Input name="contactPhone" label="Contact phone" defaultValue={org.contactPhone ?? ''} /><Button type="submit" variant="primary" disabled={busy}>Save organization</Button></form></section>{canManage && <section className="org-panel"><h2>Team and authority</h2><p>Add an active Organizer by their account ID. New members receive no permissions until you grant them.</p><form className="org-form-grid" onSubmit={e => { e.preventDefault(); void run(() => organizationApi.addMember(org.id, memberId)); setMemberId(''); }}><Input label="Organizer account ID" value={memberId} onChange={e => setMemberId(e.target.value)} required /><Button type="submit" disabled={busy}>Add member</Button></form><div className="org-member-list">{members.map(m => <article key={m.user_id} className="org-member"><strong>{m.email}</strong><small>{m.user_id}</small>{m.user_id !== org.ownerUserId && <><div className="org-grants">{authorities.map(a => <label key={a}><input type="checkbox" checked={m.grants.includes(a)} disabled={busy} onChange={e => void run(() => organizationApi.grant(org.id, m.user_id, a, e.target.checked))} />{a.replace(/_/g, ' ').toLowerCase()}</label>)}</div><Button variant="outline" disabled={busy} onClick={() => { if (window.confirm(`Remove ${m.email}?`)) void run(() => organizationApi.removeMember(org.id, m.user_id)); }}>Remove member</Button></>}</article>)}</div></section>}</>}</div></AppShell>;
}
