export const ROUTES = {
  HOME: '/',
  COMMUNITY: '/community',
  VERIFY_CERT: '/verify',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  ONBOARDING_LEARNER: '/onboarding/learner',
  ONBOARDING_ORGANIZER: '/onboarding/organizer',
  LEARNER_APP: '/app',
  ORGANIZER_APP: '/organizer',
  ORGANIZER_PENDING: '/organizer/verification-pending',
  ADMIN: '/admin',
  EXPLORE: '/explore',
  LEARNING_PATHS: '/learning-paths',
  PRACTICE: '/practice',
  CERTIFICATIONS: '/certifications',
} as const;
